# Generated by Django 5.0.3 on 2024-03-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
